import type { Template } from "./types"

const defaultTextEffects = {
  shadow: {
    enabled: false,
    offsetX: 2,
    offsetY: 2,
    blur: 4,
    color: "rgba(0,0,0,0.5)",
  },
  outline: {
    enabled: false,
    width: 2,
    color: "#000000",
  },
}

const defaultBackground = {
  imageBlur: 0,
  overlay: {
    enabled: false,
    color: "#000000",
    opacity: 0.5,
  },
  pattern: {
    type: "dots" as const,
    color: "#ffffff",
    size: 20,
    opacity: 0.1,
  },
}

export const TEMPLATES: Template[] = [
  {
    id: "professional-card",
    name: "Professional Card",
    description: "Clean and minimal business card style",
    background: {
      type: "gradient",
      color: "#1a1a2e",
      gradient: "linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #334155 100%)",
      imageUrl: "",
      imagePosition: "cover",
      ...defaultBackground,
    },
    elements: [
      {
        id: "1",
        type: "name",
        content: "John Doe",
        position: { x: 80, y: 200 },
        fontFamily: "Geist, sans-serif",
        fontSize: 64,
        fontWeight: 700,
        color: "#ffffff",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 5,
        effects: defaultTextEffects,
      },
      {
        id: "2",
        type: "custom",
        content: "Senior Product Designer",
        position: { x: 80, y: 280 },
        fontFamily: "Geist, sans-serif",
        fontSize: 24,
        fontWeight: 400,
        color: "#94a3b8",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 4,
        effects: defaultTextEffects,
      },
      {
        id: "3",
        type: "email",
        content: "john@example.com",
        position: { x: 80, y: 380 },
        fontFamily: "Geist, sans-serif",
        fontSize: 18,
        fontWeight: 400,
        color: "#64748b",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: true,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 3,
        effects: defaultTextEffects,
      },
      {
        id: "4",
        type: "twitter",
        content: "@johndoe",
        position: { x: 80, y: 420 },
        fontFamily: "Geist, sans-serif",
        fontSize: 18,
        fontWeight: 400,
        color: "#64748b",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: true,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 2,
        effects: defaultTextEffects,
      },
      {
        id: "5",
        type: "website",
        content: "johndoe.com",
        position: { x: 80, y: 460 },
        fontFamily: "Geist, sans-serif",
        fontSize: 18,
        fontWeight: 400,
        color: "#64748b",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: true,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
    ],
  },
  {
    id: "startup-launch",
    name: "Startup Launch",
    description: "Bold announcement style for product launches",
    background: {
      type: "gradient",
      color: "#1a1a2e",
      gradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
      imageUrl: "",
      imagePosition: "cover",
      ...defaultBackground,
    },
    elements: [
      {
        id: "1",
        type: "custom",
        content: "Introducing",
        position: { x: 80, y: 180 },
        fontFamily: "Geist, sans-serif",
        fontSize: 24,
        fontWeight: 400,
        color: "rgba(255,255,255,0.8)",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 4,
        effects: defaultTextEffects,
      },
      {
        id: "2",
        type: "name",
        content: "ProductName",
        position: { x: 80, y: 220 },
        fontFamily: "Geist, sans-serif",
        fontSize: 64,
        fontWeight: 700,
        color: "#ffffff",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 3,
        effects: defaultTextEffects,
      },
      {
        id: "3",
        type: "custom",
        content: "The future of productivity is here.",
        position: { x: 80, y: 320 },
        fontFamily: "Geist, sans-serif",
        fontSize: 24,
        fontWeight: 400,
        color: "rgba(255,255,255,0.9)",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 2,
        effects: defaultTextEffects,
      },
      {
        id: "4",
        type: "website",
        content: "www.productname.com",
        position: { x: 80, y: 500 },
        fontFamily: "Geist, sans-serif",
        fontSize: 18,
        fontWeight: 500,
        color: "#ffffff",
        backgroundColor: "rgba(255,255,255,0.2)",
        showBackground: true,
        textAlign: "left",
        showIcon: true,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
    ],
  },
  {
    id: "event-announcement",
    name: "Event Announcement",
    description: "Perfect for webinars and conferences",
    background: {
      type: "gradient",
      color: "#1a1a2e",
      gradient: "linear-gradient(135deg, #f12711 0%, #f5af19 100%)",
      imageUrl: "",
      imagePosition: "cover",
      ...defaultBackground,
    },
    elements: [
      {
        id: "1",
        type: "custom",
        content: "LIVE WEBINAR",
        position: { x: 80, y: 120 },
        fontFamily: "Geist, sans-serif",
        fontSize: 18,
        fontWeight: 700,
        color: "#ffffff",
        backgroundColor: "rgba(0,0,0,0.3)",
        showBackground: true,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 2,
        lineHeight: 1,
        locked: false,
        zIndex: 5,
        effects: defaultTextEffects,
      },
      {
        id: "2",
        type: "name",
        content: "Building at Scale",
        position: { x: 80, y: 200 },
        fontFamily: "Geist, sans-serif",
        fontSize: 48,
        fontWeight: 700,
        color: "#ffffff",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 4,
        effects: defaultTextEffects,
      },
      {
        id: "3",
        type: "custom",
        content: "Learn how to scale your startup from 0 to 1M users",
        position: { x: 80, y: 280 },
        fontFamily: "Geist, sans-serif",
        fontSize: 24,
        fontWeight: 400,
        color: "rgba(255,255,255,0.9)",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 3,
        effects: defaultTextEffects,
      },
      {
        id: "4",
        type: "custom",
        content: "December 20, 2025 • 2:00 PM EST",
        position: { x: 80, y: 380 },
        fontFamily: "Geist Mono, monospace",
        fontSize: 18,
        fontWeight: 500,
        color: "#ffffff",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 2,
        effects: defaultTextEffects,
      },
      {
        id: "5",
        type: "custom",
        content: "Register Now →",
        position: { x: 80, y: 480 },
        fontFamily: "Geist, sans-serif",
        fontSize: 24,
        fontWeight: 700,
        color: "#000000",
        backgroundColor: "#ffffff",
        showBackground: true,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
    ],
  },
  {
    id: "blog-post",
    name: "Blog Post",
    description: "Clean article preview style",
    background: {
      type: "gradient",
      color: "#1a1a2e",
      gradient: "linear-gradient(135deg, #134e5e 0%, #71b280 100%)",
      imageUrl: "",
      imagePosition: "cover",
      ...defaultBackground,
    },
    elements: [
      {
        id: "1",
        type: "custom",
        content: "ARTICLE",
        position: { x: 80, y: 150 },
        fontFamily: "Geist Mono, monospace",
        fontSize: 14,
        fontWeight: 500,
        color: "rgba(255,255,255,0.7)",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 3,
        lineHeight: 1,
        locked: false,
        zIndex: 4,
        effects: defaultTextEffects,
      },
      {
        id: "2",
        type: "name",
        content: "10 Tips for Better Code Reviews",
        position: { x: 80, y: 190 },
        fontFamily: "Geist, sans-serif",
        fontSize: 48,
        fontWeight: 700,
        color: "#ffffff",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 3,
        effects: defaultTextEffects,
      },
      {
        id: "3",
        type: "custom",
        content: "A comprehensive guide to improving your team's code review process.",
        position: { x: 80, y: 320 },
        fontFamily: "Geist, sans-serif",
        fontSize: 20,
        fontWeight: 400,
        color: "rgba(255,255,255,0.85)",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 2,
        effects: defaultTextEffects,
      },
      {
        id: "4",
        type: "custom",
        content: "By Sarah Chen • 8 min read",
        position: { x: 80, y: 480 },
        fontFamily: "Geist, sans-serif",
        fontSize: 16,
        fontWeight: 400,
        color: "rgba(255,255,255,0.6)",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
    ],
  },
  {
    id: "developer-portfolio",
    name: "Developer Portfolio",
    description: "Tech-focused personal branding",
    background: {
      type: "gradient",
      color: "#1a1a2e",
      gradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
      imageUrl: "",
      imagePosition: "cover",
      ...defaultBackground,
    },
    elements: [
      {
        id: "1",
        type: "custom",
        content: "{ }",
        position: { x: 80, y: 120 },
        fontFamily: "Geist Mono, monospace",
        fontSize: 32,
        fontWeight: 700,
        color: "#00c6ff",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 6,
        effects: defaultTextEffects,
      },
      {
        id: "2",
        type: "name",
        content: "Alex Developer",
        position: { x: 80, y: 200 },
        fontFamily: "Geist, sans-serif",
        fontSize: 56,
        fontWeight: 700,
        color: "#ffffff",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 5,
        effects: defaultTextEffects,
      },
      {
        id: "3",
        type: "custom",
        content: "Full-Stack Engineer • Open Source Contributor",
        position: { x: 80, y: 280 },
        fontFamily: "Geist, sans-serif",
        fontSize: 20,
        fontWeight: 400,
        color: "#94a3b8",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 4,
        effects: defaultTextEffects,
      },
      {
        id: "4",
        type: "github",
        content: "github.com/alexdev",
        position: { x: 80, y: 400 },
        fontFamily: "Geist, sans-serif",
        fontSize: 18,
        fontWeight: 400,
        color: "#64748b",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: true,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 3,
        effects: defaultTextEffects,
      },
      {
        id: "5",
        type: "twitter",
        content: "@alexdev",
        position: { x: 80, y: 440 },
        fontFamily: "Geist, sans-serif",
        fontSize: 18,
        fontWeight: 400,
        color: "#64748b",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: true,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 2,
        effects: defaultTextEffects,
      },
      {
        id: "6",
        type: "linkedin",
        content: "linkedin.com/in/alexdev",
        position: { x: 80, y: 480 },
        fontFamily: "Geist, sans-serif",
        fontSize: 18,
        fontWeight: 400,
        color: "#64748b",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: true,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
    ],
  },
  {
    id: "minimal-quote",
    name: "Minimal Quote",
    description: "Elegant quote or testimonial",
    background: {
      type: "solid",
      color: "#0f172a",
      gradient: "",
      imageUrl: "",
      imagePosition: "cover",
      ...defaultBackground,
    },
    elements: [
      {
        id: "1",
        type: "custom",
        content: '"',
        position: { x: 60, y: 120 },
        fontFamily: "Georgia, serif",
        fontSize: 120,
        fontWeight: 400,
        color: "#334155",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 3,
        effects: defaultTextEffects,
      },
      {
        id: "2",
        type: "name",
        content: "Design is not just what it looks like. Design is how it works.",
        position: { x: 80, y: 200 },
        fontFamily: "Georgia, serif",
        fontSize: 36,
        fontWeight: 400,
        color: "#ffffff",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1.4,
        locked: false,
        zIndex: 2,
        effects: defaultTextEffects,
      },
      {
        id: "3",
        type: "custom",
        content: "— Steve Jobs",
        position: { x: 80, y: 420 },
        fontFamily: "Geist, sans-serif",
        fontSize: 20,
        fontWeight: 500,
        color: "#64748b",
        backgroundColor: "rgba(0,0,0,0.5)",
        showBackground: false,
        textAlign: "left",
        showIcon: false,
        rotation: 0,
        letterSpacing: 0,
        lineHeight: 1,
        locked: false,
        zIndex: 1,
        effects: defaultTextEffects,
      },
    ],
  },
]
